[deps]

Plots          = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
LaTeXStrings   = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"

[compat]
julia = "1.3"
